// external
use pyo3::prelude::*;
use rand::Rng;

use crate::misc::hist_memory;

#[pyclass]
#[derive(Clone)]
pub struct CHP {
    #[pyo3(get)]
    pub pow_e: f32,  // electrical power of chp plant [W]
    #[pyo3(get)]
    pub pow_t: f32,  // installed power of chp plant [W]
    #[pyo3(get)]
    efficiency: f32, // total efficiency of chp 0 .. 1

    state: bool,  // on/off switch for chp plant

    #[pyo3(get)]
    gen_t: Option<hist_memory::HistMemory>,
    #[pyo3(get)]
    gen_e: Option<hist_memory::HistMemory>,
    #[pyo3(get)]
    fuel_used: Option<hist_memory::HistMemory>
}

#[pymethods]
impl CHP {
    ///  Create CHP plant
    ///  Parameters are power of CHP plant
    ///  The technical design is based on norm heating load and hot water use.
    ///
    /// # Arguments
    /// * power_t (f32): installed thermal chp power [W]
    /// * hist (usize): Size of history memory (0 for no memory)
    #[new]
    pub fn new(power_t: f32, hist: usize) -> Self {

        if power_t < 0. {
            panic!("Installed thermal power of chp \
                    must be greater than 0")
        }

        let pow_t = power_t;
        let pow_e = 0.5 * pow_t;

        let state = false;

        let (gen_e, gen_t, fuel_used) =
            if hist > 0 {
                (Some(hist_memory::HistMemory::new(hist)),
                 Some(hist_memory::HistMemory::new(hist)),
                 Some(hist_memory::HistMemory::new(hist)))
            } else {
                (None, None, None)
            };

        let mut rng = rand::thread_rng();
        let efficiency: f32 = rng.gen_range(0.8..=0.9);

        CHP {pow_e,
             pow_t,
             state,
             efficiency,
             gen_e,
             gen_t,
             fuel_used
             }
    }

    pub fn set_efficiency(&mut self, efficiency: f32) {
        if (efficiency < 0.) | (efficiency > 1.) {
            panic!("Efficiency must be between 0 and 1");
        } else {
            self.efficiency = efficiency;
        }
    }
}

/// CHP plant
impl CHP {
    /// Calculate the fuel power needed to provide given electrical and thermal
    /// power.
    ///
    /// # Arguments
    /// * pow_e (f32): electrical power generated by chp [W]
    /// * pow_t (f32): thermal power generated by chp [W]
    ///
    /// # Returns
    /// f32: Power of fuel needed to provide given electrical and
    ///      thermal power [W]s
    fn get_fuel(&self, pow_e: &f32, pow_t: &f32) -> f32 {
        (pow_e + pow_t) / self.efficiency
    }

    fn save_hist(&mut self, pow_e: &f32, pow_t: &f32, fuel_used: &f32) {
        match &mut self.gen_e {
            None => {},
            Some(gen_e) => {
                gen_e.save(*pow_e)
            },
        }
        match &mut self.gen_t {
            None => {},
            Some(gen_t) => {
                gen_t.save(*pow_t)
            }
        }
        match &mut self.fuel_used {
            None => {},
            Some(fuel_used_hist) => {
                fuel_used_hist.save(*fuel_used)
            }
        }
    }

    /// Calculate current electrical and thermal power
    ///
    /// # Arguments
    /// * state (&bool): Current state of CHP plant (on/off)
    ///
    /// # Returns
    /// * (f32, f32, f32): Resulting electrical and thermal power and fuel used [W]
    pub fn step(&mut self, state: &bool) -> (f32, f32, f32) {

        // update state
        self.state = *state;

        // calculate power output
        let pow_t;
        let pow_e;
        if self.state {
            pow_t = self.pow_t;
            pow_e = self.pow_e;
        }
        else {
            pow_t = 0.0;
            pow_e = 0.0;
        }

        let fuel_used = self.get_fuel(&pow_e, &pow_t);
        // save and return data
        self.save_hist(&pow_e, &pow_t, &fuel_used);

        return (pow_e, pow_t, fuel_used);
    }
}